releases/20210522110939/config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',                     to: 'static_pages#about'
  get    '/manager',                   to: 'static_pages#manager'
  get    '/signup',                    to: 'users#new'
  get    '/login',                     to: 'sessions#new'
  post   '/login',                     to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get    '/clubs/taiikukai_kyugi',     to: 'clubs#taiikukai_kyugi'
  get    '/clubs/taiikukai_budo',      to: 'clubs#taiikukai_budo'
  get    '/clubs/taiikukai_rikujou',   to: 'clubs#taiikukai_rikujou'
  get    '/clubs/taiikukai_marine',    to: 'clubs#taiikukai_marine'
  get    '/clubs/taiikukai_sonota',    to: 'clubs#taiikukai_sonota'
  get    '/clubs/sports_kyugi',        to: 'clubs#sports_kyugi'
  get    '/clubs/sports_sonota',       to: 'clubs#sports_sonota'
  get    '/clubs/bunkakai_ongaku',     to: 'clubs#bunkakai_ongaku'
  get    '/clubs/bunkakai_geijutsu',   to: 'clubs#bunkakai_geijutsu'
  get    '/clubs/bunkakei_ongaku',     to: 'clubs#bunkakei_ongaku'
  get    '/clubs/bunkakei_geijutsu',   to: 'clubs#bunkakei_geijutsu'
  get    '/clubs/bunkakei_volunteer',  to: 'clubs#bunkakei_volunteer'
  get    '/clubs/bunkakei_kokusai',    to: 'clubs#bunkakei_kokusai'
  get    '/clubs/bunkakei_sonota',     to: 'clubs#bunkakei_sonota'
  get    '/clubs/iinkai',              to: 'clubs#iinkai'
  get    '/likes/:club_id/create',     to: 'likes#create'
  get    '/contacts/thanks',           to: 'contacts#thanks'
  get    '/credits/search',            to: 'credits#search'
  get    '/credits/easy',              to: 'credits#easy'
  get    '/credits/full',              to: 'credits#full'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :manuscripts
  resources :credits,             only: [:index, :new, :create, :destroy]
  resources :clubs,               only: [:index, :show, :new, :create, :edit, :update]
  resources :events
  resources :contacts,            only: [:index, :show, :new, :create]
end

releases/20210522110939/app/models/event.rb
class Event < ApplicationRecord
end

releases/20210522110939/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_user, only: [:new, :create, :edit, :destroy]
  
  def index
    @events = Event.paginate(page: params[:page]).order("created_at DESC")
  end
  
  def show
    @event = Event.find(params[:id])
  end

  def new
  end
  
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      flash.now[:danger] = @event.errors.full_messages
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path
    else
      flash.now[:danger] = "invalid"
      render 'edit'
    end
  end
  
  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "complite"
    redirect_to events_path
  end
  
  private
  
    def event_params
      params.require(:event).permit(:title, :content)
    end
  
end

releases/20210522110939/app/helpers/events_helper.rb
module EventsHelper
end

releases/20210522110939/app/views/events/_event.html.erb
<%= link_to event_path(event) do %>
  <div class="frame">
    <picture>
      <%= image_tag "static_pages/orange.jpg" %>
    </picture>
    <div class="letters">
      <h2><%= event.title %></h2>
      <p><%= event.created_at.to_s(:datetime_jp) %></p>
      <% if current_user && current_user.admin? %>
        <%= link_to "編集", edit_event_path(event) %>
        <%= link_to "削除", event_path(event), method: :delete,
                                         data: { confirm: "You sure?" }%>
      <% end %>
    </div>
  </div>
<% end %>

releases/20210522110939/app/views/events/edit.html.erb
<%= provide(:title, 'Event edit') %>
<div class="form-title">
  <h1>Event form edit</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @event, local: true) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content %>
      
      <%= f.submit "Create manuscript", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

releases/20210522110939/app/views/events/index.html.erb
<%= provide(:title, 'Event List') %>

  <div class="box-design common">
    <h1>University Event</h1>
    <% if current_user && current_user.admin? %>
      <div class="admin_post">
        <%= link_to "Event投稿", new_event_path %>
      </div>
    <% end %>
    
    <%= will_paginate %>
     
    <div class="box-container">
      <%= render @events %>
    </div>
    
    <%= will_paginate %>
    
  </div>

releases/20210522110939/app/views/events/new.html.erb
<%= provide(:title, 'Event Form') %>
<div class="form-title">
  <h1>Event form</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: events_path, scope: :event, local: true) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content %>
      
      <%= f.submit "Create manuscript", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

releases/20210522110939/app/views/events/show.html.erb
<%= provide(:title, @event.title) %>

<div class="manuscript-event-contact-show">
  <h1><%= @event.title %></h1>
  <p><%= @event.content %></p>
</div>