releases/20210522110939/config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',                     to: 'static_pages#about'
  get    '/manager',                   to: 'static_pages#manager'
  get    '/signup',                    to: 'users#new'
  get    '/login',                     to: 'sessions#new'
  post   '/login',                     to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get    '/clubs/taiikukai_kyugi',     to: 'clubs#taiikukai_kyugi'
  get    '/clubs/taiikukai_budo',      to: 'clubs#taiikukai_budo'
  get    '/clubs/taiikukai_rikujou',   to: 'clubs#taiikukai_rikujou'
  get    '/clubs/taiikukai_marine',    to: 'clubs#taiikukai_marine'
  get    '/clubs/taiikukai_sonota',    to: 'clubs#taiikukai_sonota'
  get    '/clubs/sports_kyugi',        to: 'clubs#sports_kyugi'
  get    '/clubs/sports_sonota',       to: 'clubs#sports_sonota'
  get    '/clubs/bunkakai_ongaku',     to: 'clubs#bunkakai_ongaku'
  get    '/clubs/bunkakai_geijutsu',   to: 'clubs#bunkakai_geijutsu'
  get    '/clubs/bunkakei_ongaku',     to: 'clubs#bunkakei_ongaku'
  get    '/clubs/bunkakei_geijutsu',   to: 'clubs#bunkakei_geijutsu'
  get    '/clubs/bunkakei_volunteer',  to: 'clubs#bunkakei_volunteer'
  get    '/clubs/bunkakei_kokusai',    to: 'clubs#bunkakei_kokusai'
  get    '/clubs/bunkakei_sonota',     to: 'clubs#bunkakei_sonota'
  get    '/clubs/iinkai',              to: 'clubs#iinkai'
  get    '/likes/:club_id/create',     to: 'likes#create'
  get    '/contacts/thanks',           to: 'contacts#thanks'
  get    '/credits/search',            to: 'credits#search'
  get    '/credits/easy',              to: 'credits#easy'
  get    '/credits/full',              to: 'credits#full'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :manuscripts
  resources :credits,             only: [:index, :new, :create, :destroy]
  resources :clubs,               only: [:index, :show, :new, :create, :edit, :update]
  resources :events
  resources :contacts,            only: [:index, :show, :new, :create]
end

releases/20210522110939/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "ご意見・ご要望", new_contact_path %></li>
      <li><%= link_to "開発者紹介", manager_path %></li>
    </ul>
  </nav>
</footer>

releases/20210522110939/app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

releases/20210522110939/app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<%= javascript_pack_tag 'application',
                            'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

releases/20210522110939/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

releases/20210522110939/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>