releases/20210522110939/config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',                     to: 'static_pages#about'
  get    '/manager',                   to: 'static_pages#manager'
  get    '/signup',                    to: 'users#new'
  get    '/login',                     to: 'sessions#new'
  post   '/login',                     to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get    '/clubs/taiikukai_kyugi',     to: 'clubs#taiikukai_kyugi'
  get    '/clubs/taiikukai_budo',      to: 'clubs#taiikukai_budo'
  get    '/clubs/taiikukai_rikujou',   to: 'clubs#taiikukai_rikujou'
  get    '/clubs/taiikukai_marine',    to: 'clubs#taiikukai_marine'
  get    '/clubs/taiikukai_sonota',    to: 'clubs#taiikukai_sonota'
  get    '/clubs/sports_kyugi',        to: 'clubs#sports_kyugi'
  get    '/clubs/sports_sonota',       to: 'clubs#sports_sonota'
  get    '/clubs/bunkakai_ongaku',     to: 'clubs#bunkakai_ongaku'
  get    '/clubs/bunkakai_geijutsu',   to: 'clubs#bunkakai_geijutsu'
  get    '/clubs/bunkakei_ongaku',     to: 'clubs#bunkakei_ongaku'
  get    '/clubs/bunkakei_geijutsu',   to: 'clubs#bunkakei_geijutsu'
  get    '/clubs/bunkakei_volunteer',  to: 'clubs#bunkakei_volunteer'
  get    '/clubs/bunkakei_kokusai',    to: 'clubs#bunkakei_kokusai'
  get    '/clubs/bunkakei_sonota',     to: 'clubs#bunkakei_sonota'
  get    '/clubs/iinkai',              to: 'clubs#iinkai'
  get    '/likes/:club_id/create',     to: 'likes#create'
  get    '/contacts/thanks',           to: 'contacts#thanks'
  get    '/credits/search',            to: 'credits#search'
  get    '/credits/easy',              to: 'credits#easy'
  get    '/credits/full',              to: 'credits#full'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :manuscripts
  resources :credits,             only: [:index, :new, :create, :destroy]
  resources :clubs,               only: [:index, :show, :new, :create, :edit, :update]
  resources :events
  resources :contacts,            only: [:index, :show, :new, :create]
end

releases/20210522110939/app/models/contact.rb
class Contact < ApplicationRecord
  validates :title,   presence: true
  validates :content, presence: true
end

releases/20210522110939/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :admin_user, only: [:index]
  
  def index
    @contacts = Contact.all.order("created_at DESC")
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "送信が完了しました。"
      redirect_to contacts_thanks_path
    else
      flash.now[:danger] = @contact.errors.full_messages
      render 'new'
    end
  end
  
  def thanks
  end
  
  private
  
    def contact_params
      params.require(:contact).permit(:title, :content, :name, :email)
    end
  
end

releases/20210522110939/app/helpers/contacts_helper.rb
module ContactsHelper
end

releases/20210522110939/app/views/contacts/index.html.erb
<%= provide(:title, 'Contact List') %>

<div class="contact-admin">
  <h1>お客様のご意見</h1>
  
  <% @contacts.each do |contact| %>
    <div class="admin-box">
      <p>
        <%= link_to contact.title, contact_path(contact) %>
        <span>
          <% unless contact.email.blank? %>
            *
          <% end %>
        </span>
      </p>
      <p><%= contact.created_at.to_s(:datetime_jp) %></p>
    </div>
  <% end %>
</div>

releases/20210522110939/app/views/contacts/new.html.erb
<% provide(:title, 'ご意見・ご要望') %>
<div class="form-title">
  <h1>ご意見・ご要望</h1>
</div>

<% if current_user && current_user.admin? %>
  <div class="admin-entrance">
    <%= link_to "管理者専用ページ", contacts_path %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 contact-new">
    <%= form_with(url: contacts_path, scope: :contact, local: true) do |f| %>
      
      <%= f.label :title, "タイトル ※必須"%>
      <%= f.text_field :title %>
      
      <%= f.label :content, "サイトの問題点やご意見、ご質問等の詳細をご入力ください。 ※必須" %>
      <%= f.text_area :content %>
      
      <p>※個別に回答を希望される方は下記の情報もご入力下さい。</p>
      
      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>

      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

releases/20210522110939/app/views/contacts/show.html.erb
<div class="manuscript-event-contact-show">
  <h1><%= @contact.title %></h1>
  <p><%= @contact.content %></p>
  
  <% unless @contact.name.blank? %>
    <div class="personal-information">
      <h3>※連絡希望</h3>
      <ul>
        <li><%= @contact.name %></li>  
        <li><%= @contact.email %></li>
      </ul>
    </div>
  <% end %>
</div>

releases/20210522110939/app/views/contacts/thanks.html.erb
<h1>貴重なご意見ありがとうございます。</h1>